<a href="https://colab.research.google.com/github/TheOohWee/CSE-10124-LAB-1/blob/main/Amir_CSE10124_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CSE 10124 - Building ChatGPT: Lab 01 (5 pts.)

- NETID:

This assignment covers the following topics:
- Character-Level Tokenization
- Simple BPE Tokenization
- BPE+Regex Tokenization

It will consist of 5 tasks:

| Task ID  | Description                                      | Points |
|----------|--------------------------------------------------|--------|
| 00       | Data + Libary Loading                          | 0      |
| 01       | BPE Tokenization                          | 1      |
| &nbsp;&nbsp;&nbsp;&nbsp;01-1     | &nbsp;&nbsp;&nbsp;&nbsp;- Encode prompt as character tokens                   |      |
| &nbsp;&nbsp;&nbsp;&nbsp;01-2     | &nbsp;&nbsp;&nbsp;&nbsp;- Write count_pairs and merge_pairs                   |      |
| &nbsp;&nbsp;&nbsp;&nbsp;01-3     | &nbsp;&nbsp;&nbsp;&nbsp;- Merge tokens in prompt                   |      |
| 02       | Simple BPE Tokenizer Class                | 2       |
| &nbsp;&nbsp;&nbsp;&nbsp;02-1     | &nbsp;&nbsp;&nbsp;&nbsp;- Fill in missing class code                   |      |
| &nbsp;&nbsp;&nbsp;&nbsp;02-2     | &nbsp;&nbsp;&nbsp;&nbsp;- Compare tokenizer on different datasets                   |      |
| 03       | BPE+Regex Tokenization                | 2       |
| &nbsp;&nbsp;&nbsp;&nbsp;03-1     | &nbsp;&nbsp;&nbsp;&nbsp;- Expand on Simple_Tokenizer class code                   |      |
| &nbsp;&nbsp;&nbsp;&nbsp;03-2     | &nbsp;&nbsp;&nbsp;&nbsp;- Compare tokenizer on different datasets                   |      |
| 04       | Generate Submission               | 0       |

Please complete all sections. Some questions will require written answers, while others will involve coding. Be sure to run your code cells to verify your solutions.

In the code blocks, look for comments like:
```python
# TODO: some task description
```
as these are what you will be expected to fill in. For code sections longer than a line, there's an additional comment:
```python
# LINES: N
```
where `N` is the number of lines I have in my solution. This is NOT graded on, it is just a reference for you, if you have way more or way fewer it may be worth rethinking your code but +/- 2-3 lines is nothing to worry about usually.


## Task 00: Load Data and Libraries (0 pts.)
#### Loading Data and Importing Libraries

Run the cell below to download the data and libraries and then import our utilities library

### Task 00: Code (0 pts.)

In [ ]:
import os

try:
    import google.colab
    REPO_URL = "https://github.com/wtheisen/nd-cse-10124-lectures.git"

    REPO_NAME = "/content/nd-cse-10124-lectures"
    L_PATH = "nd-cse-10124-lectures"

    %cd /content/
    !rm -r {REPO_NAME}

    # Clone repo
    if not os.path.exists(REPO_NAME):
        !git clone {REPO_URL}

        # cd into the data folder
        %cd {L_PATH}
        !pwd

except ImportError:
    print("Unable to download repo, either:")
    print("\tA.) You're not on colab")
    print("\tB.) It has already been cloned")

import irishGPT.utilities as uts

/content
Cloning into 'nd-cse-10124-lectures'...
remote: Enumerating objects: 466, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 466 (delta 19), reused 41 (delta 11), pack-reused 411 (from 1)
Receiving objects: 100% (466/466), 60.58 MiB | 41.47 MiB/s, done.
Resolving deltas: 100% (282/282), done.
/content/nd-cse-10124-lectures
/content/nd-cse-10124-lectures


## Task 01: Strings to Bytes
### Task 01-1: Description (0 pts.)
#### Loading Data and Printing Bytes

In the cell below, write code to print the following string, along with its tokens.

`'rug pug hug pun bun hugs run gun bug'`

### Task 01-1: Code (0 pts.)

In [ ]:
# TODO: add the string to a variable called "prompt"
prompt = "rug pug hug pun bun hugs run gun bug"
# TODO: Print the variable
print(prompt)
# TODO: print the variables tokens
print(list(prompt.encode('utf-8')))

rug pug hug pun bun hugs run gun bug
[114, 117, 103, 32, 112, 117, 103, 32, 104, 117, 103, 32, 112, 117, 110, 32, 98, 117, 110, 32, 104, 117, 103, 115, 32, 114, 117, 110, 32, 103, 117, 110, 32, 98, 117, 103]


### Task 01-1: Expected Output (0 pts.)
```
rug pug hug pun bun hugs run gun bug
[114, 117, 103, 32, 112, 117, 103, 32, 104, 117, 103, 32, 112, 117, 110, 32, 98, 117, 110, 32, 104, 117, 103, 115, 32, 114, 117, 110, 32, 103, 117, 110, 32, 98, 117, 103]
```

### Task 01-2: Description (0 pts.)
#### Counting and merging repetitive pairs

Clearly there are many repeating pairs of tokens in this list, particularly:
`(117, 103)` and `(117, 110)` which are the character-tokens for `ug` and `un`.

Byte-Pair Encoding works by repeatedly finding these pairs and then combining them into a new token!

In the code cell below, finish the two functions to:
1. Find and count pairs of tokens
2. Combine the target pair into a new token

Then run the two functions on our prompt from above, printing out the length of the prompt before and after running the functions

### Task 01-2: Code (0.5 pts.)

In [ ]:
from collections import Counter

def count_pairs(tokens):
    pair_counts = Counter()

    # TODO: Finish the count_pairs function
    # LINES: 2

    for pair in zip(tokens, tokens[1:]):

      # zip stitches 2 lists together creating sort of list of lists
      # tokens[1:] is called slicing: so tokens[1:] starts from index 1
      # tokens[start:stop]

        pair_counts[pair] += 1

    return pair_counts

def merge_pair(tokens, target_pair, combined_id):
    merged_tokens = []

    # TODO: Finish the merge_pair function
    # LINES: 8

    i = 0 # to track where we are in the list
    while i < len(tokens):
      if i < len(tokens) - 1 and (tokens[i], tokens[i+1]) == target_pair:
        merged_tokens.append(combined_id)
        i += 2
      else:
        merged_tokens.append(tokens[i])
        i += 1

    return merged_tokens

'''
overview:
1. count_pairs just counts the number of all consequitive pairs, we will use most_common pair in pair_counts
2. merge_pair goes through the list of tokens and then just merges the 2 tokens that are the most common pair
'''

'\noverview:\n1. count_pairs just counts the number of all consequitive pairs, we will use most_common pair in pair_counts\n2. merge_pair goes through the list of tokens and then just merges the 2 tokens that are the most common pair\n'

### Task 01-3: Description (0 pts.)
#### Testing our Functions

In the cell below, test your two functions by merging the most common token pair in our prompt and print and compare the two outputs

### Task 01-3: Code (0 pts.)

In [ ]:
prompt = 'rug pug hug pun bun hugs run gun bug'

print('Length of prompt before merging:', len(list(prompt.encode('utf-8'))))
print('Unmerged Prompt:', list(prompt.encode('utf-8')))

# TODO: Count the pairs of our prompt
pairs_counts = count_pairs(list(prompt.encode('utf-8')))

# TODO: Find the most common pair

most_common_pair = pairs_counts.most_common()[0][0]

# TODO: Merge the most common pair in our prompt, using token id 257 as the new token
merged_tokens = merge_pair(list(prompt.encode('utf-8')), most_common_pair, 257)

print('Length of prompt after merging:', len(merged_tokens))
print('Merged Prompt:', merged_tokens)

Length of prompt before merging: 36
Unmerged Prompt: [114, 117, 103, 32, 112, 117, 103, 32, 104, 117, 103, 32, 112, 117, 110, 32, 98, 117, 110, 32, 104, 117, 103, 115, 32, 114, 117, 110, 32, 103, 117, 110, 32, 98, 117, 103]
Length of prompt after merging: 31
Merged Prompt: [114, 257, 32, 112, 257, 32, 104, 257, 32, 112, 117, 110, 32, 98, 117, 110, 32, 104, 257, 115, 32, 114, 117, 110, 32, 103, 117, 110, 32, 98, 257]


### Task 01-3: Expected Output (0.25 pts.)
```
Length of prompt before merging: 36
Unmerged Prompt: [114, 117, 103, 32, 112, 117, 103, 32, 104, 117, 103, 32, 112, 117, 110, 32, 98, 117, 110, 32, 104, 117, 103, 115, 32, 114, 117, 110, 32, 103, 117, 110, 32, 98, 117, 103]
Length of prompt after merging: 31
Merged Prompt: [114, 257, 32, 112, 257, 32, 104, 257, 32, 112, 117, 110, 32, 98, 117, 110, 32, 104, 257, 115, 32, 114, 117, 110, 32, 103, 117, 110, 32, 98, 257]
```

## Task 02: Simple BPE Tokenizer Class
### Task 02-1: Description (0 pts.)
#### Simple BPE Tokenizer Class

In the cell below, fill out the code to complete the class for our simple tokenizer.

### Task 02-1: Code (1 pt.)

In [ ]:
"""
Minimal (byte-level) Byte Pair Encoding tokenizer.

Algorithmically follows along the GPT tokenizer:
https://github.com/openai/gpt-2/blob/master/src/encoder.py
"""

class Simple_Tokenizer():
    def __init__(self):
        self.merges = {} # (int, int) -> int

        self.special_tokens = {'<|sos|>': 256, '<|eos|>': 257}

        self.vocab = {idx: bytes([idx]) for idx in range(256)}

        self.vocab[256] = '<|sos|>'
        self.vocab[257] = '<|eos|>'


    def _count_pairs(self, tokens, counts=None):
        pair_counts = Counter()

        # TODO: Finish the _count_pairs function
        # LINES: 2
        for pair in zip(tokens, tokens[1:]):
          pair_counts[pair] += 1


        return pair_counts


    def _merge_pair(self, tokens, target_pair, combined_id):
        merged_tokens = []

        # TODO: Finish the _merge_pair function
        # LINES: 8
        i = 0 # to track where we are in the list
        while i < len(tokens):
          if i < len(tokens) - 1 and (tokens[i], tokens[i+1]) == target_pair:
            merged_tokens.append(combined_id)
            i += 2
          else:
            merged_tokens.append(tokens[i])
            i += 1

        return merged_tokens

    def train(self, text, max_vocab_size=1024):
        vocab_size = len(self.vocab)
        num_merges = max_vocab_size - vocab_size

        text_bytes = text.encode('utf-8')
        tokens = list(text_bytes)

        for i in range(num_merges):
            # TODO: Count the pairs
            pairs = self._count_pairs(tokens)

            # This code will handle us having no more pairs to merge
            try:
                target_pair = pairs.most_common()[0][0]
            except:
                break

            # TODO: Calculate the id for our new pair
            combined_id = vocab_size + i
            # TODO: Merge the pair with the new id
            tokens = self._merge_pair(tokens, target_pair, combined_id)
            # TODO: Save the id for the new pair in self.merges {pair -> id}
            self.merges[target_pair] = combined_id
            # TODO: Save what the id represents in self.vocab {id -> str}
            self.vocab[combined_id] = self.vocab[target_pair[0]] + self.vocab[target_pair[1]]

    def decode(self, tokens):
        text_bytes = b''.join(self.vocab[token] for token in tokens)

        return text_bytes.decode('utf-8')

    def encode(self, text):
        text_bytes = text.encode('utf-8')
        tokens = list(text_bytes)

        while len(tokens) >= 2:
            pairs = self._count_pairs(tokens)

            earliest_pair = min(pairs, key=lambda p: self.merges.get(p, float("inf")))

            if earliest_pair not in self.merges:
                break

            pair_token_id = self.merges[earliest_pair]
            tokens = self._merge_pair(tokens, earliest_pair, pair_token_id)

        return tokens

### Task 02-2: Description (0 pts.)
#### Testing the Class

Now that we have our Simple Tokenizer, lets train it on two different datasets and see how that effects the tokenization of our simple prompt. In the cell below create and train a `Simple_Tokenizer()` with a vocabulary size of `512` on the following three datasets:

1. `Datasets/jabberwocky.txt`
2. `Datasets/zoomer.txt`
3. `Datasets/shakespeare.txt`

**Note:** The Shakespeare one will take quite a while to train (~10 minutes) so please be patient and let it run

See if you notice any differences between the three and consider why that might happen.

### Task 02-2: Code

In [ ]:
prompt = 'rug pug hug pun bun hugs run gun bug'
print(list(prompt.encode('utf-8')))

jabberwocky_training_str = uts.get_file_as_string('Datasets/jabberwocky.txt')
zoomer_training_str = uts.get_file_as_string('Datasets/zoomer.txt')
shakespeare_training_str = uts.get_file_as_string('Datasets/shakespeare.txt')

# TODO: Create a Regex_Tokenizer()
jabber_tokenizer = Simple_Tokenizer()

# TODO: Train it on the jabberwocky_training_str with a vocab of 512
jabber_tokenizer.train(jabberwocky_training_str, 512)

print('Jabberwocky Tokenization of Prompt:', jabber_tokenizer.encode(prompt))

# TODO: Create a Regex_Tokenizer()
zoomer_tokenizer = Simple_Tokenizer()

# TODO: Train it on the zoomer_training_str with a vocab of 512
zoomer_tokenizer.train(zoomer_training_str, 512)

print('Zoomer Tokenization of Prompt:', zoomer_tokenizer.encode(prompt))

# TODO: Create a Regex_Tokenizer()
shakes_tokenizer = Simple_Tokenizer()

# TODO: Train it on the shakespeare_training_str with a vocab of 512
shakes_tokenizer.train(shakespeare_training_str, 512)

print('Shakespearean Tokenization of Prompt:', shakes_tokenizer.encode(prompt))

[114, 117, 103, 32, 112, 117, 103, 32, 104, 117, 103, 32, 112, 117, 110, 32, 98, 117, 110, 32, 104, 117, 103, 115, 32, 114, 117, 110, 32, 103, 117, 110, 32, 98, 117, 103]
Jabberwocky Tokenization of Prompt: [114, 117, 409, 112, 117, 409, 104, 117, 409, 112, 117, 110, 312, 117, 110, 32, 104, 117, 103, 261, 114, 117, 110, 32, 103, 117, 110, 312, 117, 103]
Zoomer Tokenization of Prompt: [114, 117, 103, 32, 112, 117, 103, 32, 104, 117, 103, 32, 112, 117, 373, 348, 373, 104, 117, 103, 262, 114, 117, 373, 103, 117, 373, 348, 103]
Shakespearean Tokenization of Prompt: [409, 103, 32, 112, 117, 103, 299, 117, 103, 32, 112, 334, 32, 98, 334, 299, 117, 103, 261, 114, 334, 32, 103, 334, 32, 98, 117, 103]


### Task 02-2: Expected Output (1 pt.)
```
[114, 117, 103, 32, 112, 117, 103, 32, 104, 117, 103, 32, 112, 117, 110, 32, 98, 117, 110, 32, 104, 117, 103, 115, 32, 114, 117, 110, 32, 103, 117, 110, 32, 98, 117, 103]
Jabberwocky Tokenization of Prompt: [114, 117, 409, 112, 117, 409, 104, 117, 409, 112, 117, 110, 312, 117, 110, 32, 104, 117, 103, 261, 114, 117, 110, 32, 103, 117, 110, 312, 117, 103]
Zoomer Tokenization of Prompt: [114, 117, 103, 32, 112, 117, 103, 32, 104, 117, 103, 32, 112, 117, 373, 348, 373, 104, 117, 103, 262, 114, 117, 373, 103, 117, 373, 348, 103]
Shakespearean Tokenization of Prompt: [409, 103, 32, 112, 117, 103, 299, 117, 103, 32, 112, 334, 32, 98, 334, 299, 117, 103, 261, 114, 334, 32, 103, 334, 32, 98, 117, 103]
```

## Task 03: BPE + Regex
### Task 03-1: Description (0 pts.)
#### Using Regex on a String

Run the cell below to see how we can use a regex to split our prompt up into smaller pieces before we tokenize!

### Task 03-1: Code (0 pts.)

In [ ]:
import regex as re

GPT4_SPLIT_PATTERN = r"""'(?i:[sdmt]|ll|ve|re)|[^\r\n\p{L}\p{N}]?+\p{L}+|\p{N}{1,3}| ?[^\s\p{L}\p{N}]++[\r\n]*|\s*[\r\n]|\s+(?!\S)|\s+"""
# TO BE HONEST I NEED TO FIGURE THIS GPT'S REGEX PATTERN BUT FOR NOW IT'S ALRIGHT

regex = re.compile(GPT4_SPLIT_PATTERN)

prompt = 'rug pug hug pun bun hugs run gun bug'
print(prompt)

text_chunks = re.findall(regex, prompt)
print(text_chunks)

rug pug hug pun bun hugs run gun bug
['rug', ' pug', ' hug', ' pun', ' bun', ' hugs', ' run', ' gun', ' bug']


### Task 03-1: Expected Output (0 pts.)
```
rug pug hug pun bun hugs run gun bug
['rug', ' pug', ' hug', ' pun', ' bun', ' hugs', ' run', ' gun', ' bug']
```

### Task 03-2: Description (0 pts.)
#### Regex Tokenizer Class

In the cell below, fill out the sections marked to finish the `Regex_Tokenizer` class

### Task 03-2: Code (1 pt.)

In [ ]:
class Regex_Tokenizer():
    GPT4_SPLIT_PATTERN = r"""'(?i:[sdmt]|ll|ve|re)|[^\r\n\p{L}\p{N}]?+\p{L}+|\p{N}{1,3}| ?[^\s\p{L}\p{N}]++[\r\n]*|\s*[\r\n]|\s+(?!\S)|\s+"""

    def __init__(self):
        self.merges = {} # (int, int) -> int
        self.special_tokens = {'<|sos|>': 256, '<|eos|>': 257} # str -> int, e.g. {'<|endoftext|>': 100257}
        self.vocab = {idx: bytes([idx]) for idx in range(256)} | {idx: special.encode("utf-8") for special, idx in self.special_tokens.items()}

        self.pattern = self.GPT4_SPLIT_PATTERN
        self.compiled_pattern = re.compile(self.pattern)

    def _count_pairs(self, tokens, pair_counts=None):
        for pair in zip(tokens, tokens[1:]):
            pair_counts[pair] += 1

        return pair_counts

    def _merge_pairs(self, tokens, target_pair, combined_id):
        merged_tokens = []

        i = 0
        while i < len(tokens):
            if i < len(tokens) - 1 and (tokens[i], tokens[i+1]) == target_pair:
                merged_tokens.append(combined_id)
                i += 2
            else:
                merged_tokens.append(tokens[i])
                i += 1

        return merged_tokens

    def chunk(self, text):
        return re.findall(self.compiled_pattern, text)

    def train(self, text, max_vocab_size, verbose=False):
        pretrain_vocab_size = len(self.vocab)
        num_merges = max_vocab_size - pretrain_vocab_size

        text_chunks = re.findall(self.compiled_pattern, text)

        ids = [list(ch.encode("utf-8")) for ch in text_chunks]

        for i in range(num_merges):
            pairs = Counter()

            # TODO: for each chunk, count the number of times every consecutive pair appears
            # LINES: 2
            for chunk_ids in ids:
              pairs = self._count_pairs(chunk_ids, pairs)

            pair = pairs.most_common()[0][0]

            idx = pretrain_vocab_size + i

            ids = [self._merge_pairs(chunk_ids, pair, idx) for chunk_ids in ids]

            self.merges[pair] = idx
            self.vocab[idx] = self.vocab[pair[0]] + self.vocab[pair[1]]

    def decode(self, ids):
        # given ids (list of integers), return Python string
        part_bytes = []
        for idx in ids:
            if idx in self.vocab:
                part_bytes.append(self.vocab[idx])
            else:
                part_bytes.append('<|unk|>')

        text_bytes = b"".join(part_bytes)
        text = text_bytes.decode("utf-8", errors="replace")

        return text

    def _encode_chunk(self, text_bytes):
        # return the token ids
        ids = list(text_bytes)

        while len(ids) >= 2:
            # find the pair with the lowest merge index
            stats = self._count_pairs(ids, Counter())
            pair = min(stats, key=lambda p: self.merges.get(p, float("inf")))

            if pair not in self.merges:
                break # nothing else can be merged anymore

            idx = self.merges[pair]
            ids = self._merge_pairs(ids, pair, idx)

        return ids

    def encode(self, text):
        special_pattern = "(" + "|".join(re.escape(k) for k in self.special_tokens) + ")"
        special_chunks = re.split(special_pattern, text)

        tokens = []
        for part in special_chunks[1:-1]:
            if part in self.special_tokens:
                tokens.append(self.special_tokens[part])
            else:
                text_chunks = self.chunk(part)

                # TODO: encode each chunk of text and add the tokens to the list
                # LINES: 4
                # NOTE: You can use the _encode_chunk function above to help with this!
                for chunk in text_chunks:
                  chunk_bytes = chunk.encode('utf-8')
                  tokens.append(self._encode_chunk(chunk_bytes))

        return tokens

### Task 03-3: Description (0 pts.)
#### Testing our Regex Tokenizer

Now that we have our Regex_Tokenizer, lets test it in a similar manner to what we did in Task 02-2.

**Note:** Again the Shakespeare one will take quite a while to train (~10 minutes) so please be patient

### Task 03-3: Code (0 pts.)

In [ ]:
prompt = '<|sos|>rug pug hug pun bun hugs run gun bug<|eos|>'
print(list(prompt.encode('utf-8')))

jabberwocky_training_str = uts.get_file_as_string('Datasets/jabberwocky.txt')
zoomer_training_str = uts.get_file_as_string('Datasets/zoomer.txt')
shakespeare_training_str = uts.get_file_as_string('Datasets/shakespeare.txt')

# TODO: Create a Regex_Tokenizer()
jabber_tokenizer = Regex_Tokenizer()

# TODO: Train it on the jabberwocky_training_str with a vocab of 512
jabber_tokenizer.train(jabberwocky_training_str, 512)

print('Jabberwocky Tokenization of Prompt:', jabber_tokenizer.encode(prompt))

# TODO: Create a Regex_Tokenizer()
zoomer_tokenizer = Regex_Tokenizer()

# TODO: Train it on the zoomer_training_str with a vocab of 512
zoomer_tokenizer.train(zoomer_training_str, 512)

print('Zoomer Tokenization of Prompt:', zoomer_tokenizer.encode(prompt))

# TODO: Create a Regex_Tokenizer()
shakes_tokenizer = Regex_Tokenizer()

# TODO: Train it on the shakespeare_training_str with a vocab of 512
shakes_tokenizer.train(shakespeare_training_str, 512)

print('Shakespearean Tokenization of Prompt:', shakes_tokenizer.encode(prompt))

[60, 124, 115, 111, 115, 124, 62, 114, 117, 103, 32, 112, 117, 103, 32, 104, 117, 103, 32, 112, 117, 110, 32, 98, 117, 110, 32, 104, 117, 103, 115, 32, 114, 117, 110, 32, 103, 117, 110, 32, 98, 117, 103, 60, 124, 101, 111, 115, 124, 62]
Jabberwocky Tokenization of Prompt: [256, [114, 117, 103], [32, 112, 117, 103], [310, 117, 103], [32, 112, 117, 110], [503, 110], [310, 117, 103, 115], [314, 117, 110], [285, 117, 110], [503, 103], 257]
Zoomer Tokenization of Prompt: [256, [114, 117, 103], [293, 117, 103], [296, 117, 103], [293, 431], [276, 431], [296, 117, 103, 115], [355, 431], [286, 431], [276, 117, 103], 257]
Shakespearean Tokenization of Prompt: [256, [425, 103], [292, 117, 103], [290, 117, 103], [292, 117, 110], [270, 117, 110], [290, 117, 103, 115], [32, 425, 110], [306, 117, 110], [270, 117, 103], 257]


### Task 03-3: Expected Output (0 pts.)
```
[60, 124, 115, 111, 115, 124, 62, 114, 117, 103, 32, 112, 117, 103, 32, 104, 117, 103, 32, 112, 117, 110, 32, 98, 117, 110, 32, 104, 117, 103, 115, 32, 114, 117, 110, 32, 103, 117, 110, 32, 98, 117, 103, 60, 124, 101, 111, 115, 124, 62]
Jabberwocky Tokenization of Prompt: [256, 114, 117, 103, 32, 112, 117, 103, 310, 117, 103, 32, 112, 117, 110, 503, 110, 310, 117, 103, 115, 314, 117, 110, 285, 117, 110, 503, 103, 257]
Zoomer Tokenization of Prompt: [256, 114, 117, 103, 293, 117, 103, 296, 117, 103, 293, 431, 276, 431, 296, 117, 103, 115, 355, 431, 286, 431, 276, 117, 103, 257]
Shakespearean Tokenization of Prompt: [256, 425, 103, 292, 117, 103, 290, 117, 103, 292, 117, 110, 270, 117, 110, 290, 117, 103, 115, 32, 425, 110, 306, 117, 110, 270, 117, 103, 257]
```

## Task 05: Generate Submission
### Task 05: Description (0 pts.)

Uncomment the function call at the end of the code block to generate the file to submit on canvas.

### Task 05: Code (0 pts.)

In [ ]:
import os, json

def export_notebook():
    L_PATH = "nd-cse-10124-lectures/Notebooks"
    L = "Lab_01_Tokenization"

    try:
        from google.colab import _message, files

        repo_ipynb_path = f"/content/{L_PATH}/{L}.ipynb"
        nb = _message.blocking_request("get_ipynb", timeout_sec=1)["ipynb"]

        os.makedirs(os.path.dirname(repo_ipynb_path), exist_ok=True)
        with open(repo_ipynb_path, "w", encoding="utf-8") as f:
            json.dump(nb, f)

        !jupyter nbconvert --to html "{repo_ipynb_path}"
        files.download(repo_ipynb_path.replace(".ipynb", ".html"))
    except:
        import subprocess
        nb_fp = os.getcwd() + f'/{L}.ipynb'
        subprocess.run(["jupyter", "nbconvert", "--to", "html", nb_fp], check=True)

# TODO: Uncomment the line below and run to generate the file to submit on canvas
export_notebook()

[NbConvertApp] Converting notebook /content/nd-cse-10124-lectures/Notebooks/Lab_01_Tokenization.ipynb to html
[NbConvertApp] Writing 358025 bytes to /content/nd-cse-10124-lectures/Notebooks/Lab_01_Tokenization.html


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>